
export const DECK_OPTIONS = {
    DECK_MAX_NAME_LENGTH: 30,
    DECK_MAX_DESCRIPTION_LENGTH: 500,
    DECK_RESULT_FETCH_LIMIT: 40,
    CARD_RESULT_FETCH_LIMIT: 15,
    REVIEW_RESULT_FETCH_LIMIT: 15,
    STUDY_CARD_FETCH_LIMIT: 40
}

export const DICT_OPTIONS = {
    MAX_QUERY_LENGTH: 300,
    ENTRY_RESULT_FETCH_LIMIT: 10
}