
export const DECK_OPTIONS = {
    DECK_MAX_NAME_LENGTH: 30,
    DECK_MAX_DESCRIPTION_LENGTH: 500,
    DECK_RESULT_FETCH_LIMIT: 5,
    CARD_RESULT_FETCH_LIMIT: 15,
    REVIEW_RESULT_FETCH_LIMIT: 15,
}

export const DICT_OPTIONS = {
    MAX_QUERY_LENGTH: 300,
    MAX_RESULTS_PER_PAGE: 20,
}

export const STUDY_OPTIONS = {
    FETCH_NEW_CARD_WHEN_LENGTH: 10,
    CARD_FETCH_LIMIT: 40
}